// Generated by CoffeeScript 1.6.3
(function() {
  if (!Function.prototype.method) {
    Function.prototype.method = function(name, func) {
      if (!this.prototype[name]) {
        this.prototype[name] = func;
      }
      return this;
    };
  }

  String.method('join', function() {
    var arr;
    arr = Array.prototype.slice.call(arguments, 0);
    arr.unshift(this);
    return arr.join('');
  });

  String.method('trim', function() {
    return this.replace(/^\s+|\s+$/g, '');
  });

  String.method('reverse', function() {
    return this.split().reverse().join('');
  });

  Array.method('forEach', function(parse, scope) {
    var item, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = this.length; _i < _len; _i++) {
      item = this[_i];
      _results.push(parse(item));
    }
    return _results;
  });

}).call(this);
